name: wan_android
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_flip_counter: ^0.2.1
  beamer: ^1.5.3
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  cookie_jar: ^3.0.1
  cupertino_icons: ^1.0.2
  custom_pop_up_menu: ^1.2.4
  diox: ^5.0.0-dev.2
  diox_cookie_manager: ^2.1.0-dev.1
  extended_image: ^6.2.0
  extended_sliver: ^2.1.3
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_riverpod: ^2.1.3
  flutter_slidable: ^2.0.0
  flutter_smart_dialog: ^4.7.3
  flutter_svg: ^1.0.0
  freezed_annotation: ^2.2.0
  html: ^0.15.0
  html_unescape: ^2.0.0
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_annotation: ^4.6.0
  logging: ^1.0.2
  native_diox_adapter:
    git:
      url: git@github.com:cfug/diox.git
      ref: main
      path: plugins/native_diox_adapter
  nil: ^1.1.1
  palette_generator: ^0.3.3
  path_provider: ^2.0.8
  shimmer: ^2.0.0
  url_launcher: ^6.1.0

dev_dependencies:
  build_runner: ^2.1.5
  dart_code_metrics: ^5.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  isar_generator: ^3.0.5
  json_serializable: ^6.5.4


flutter:
  uses-material-design: true

  assets:

  # assets start

  # GENERATED CODE - DO NOT MODIFY MANUALLY
  # **************************************************************************
  # Auto generated by https://github.com/fluttercandies/assets_generator
  # **************************************************************************

    - assets/images/

  # assets end
  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/icon_font.ttf

flutter_intl:
  enabled: true
  arb_dir: lib/app/l10n
  output_dir: lib/app/l10n/generated