name: wan_android
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_flip_counter: ^0.2.1
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  cookie_jar: ^3.0.1
  cupertino_icons: ^1.0.2
  custom_pop_up_menu: ^1.2.4
  dio: ^5.0.0
  dio_cookie_manager: ^2.1.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.3.5
  flutter_slidable: ^2.0.0
  flutter_smart_dialog: ^4.8.2+4
  flutter_svg: ^2.0.4
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^6.0.1
  html: ^0.15.0
  html_unescape: ^2.0.0
  intl: ^0.18.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_annotation: ^4.8.0
  logging: ^1.0.2
  nil: ^1.1.1
  package_info_plus: ^3.0.2
  palette_generator: ^0.3.3
  path_provider: ^2.0.8
  riverpod_annotation: ^2.0.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.0

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^1.0.16
  intl_utils: ^2.8.1
  isar_generator: ^3.0.5
  json_serializable: ^6.6.1
  riverpod_generator: ^2.2.0
  riverpod_lint: ^1.3.0


flutter:
  uses-material-design: true

  assets:

  # assets start

  # GENERATED CODE - DO NOT MODIFY MANUALLY
  # **************************************************************************
  # Auto generated by https://github.com/fluttercandies/assets_generator
  # **************************************************************************

    - assets/images/

  # assets end
  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/icon_font.ttf

flutter_intl:
  enabled: true
  arb_dir: lib/app/l10n
  output_dir: lib/app/l10n/generated