name: wan_android
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_flip_counter: ^0.2.1
  collection: ^1.17.1
  connectivity_plus: ^4.0.0
  cookie_jar: ^4.0.2
  cupertino_icons: ^1.0.2
  custom_pop_up_menu: ^1.2.4
  dio: ^5.3.2
  dio_cookie_manager: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_riverpod: ^2.3.10
  flutter_slidable: ^3.0.0
  flutter_smart_dialog: ^4.9.4
  flutter_svg: ^2.0.4
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^11.0.0
  html: ^0.15.0
  html_unescape: ^2.0.0
  intl: ^0.18.0
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.8.1
  logging: ^1.0.2
  nil: ^1.1.1
  package_info_plus: ^4.0.0
  palette_generator: ^0.3.3
  path_provider: ^2.1.0
  riverpod_annotation: ^2.1.4
  shimmer: ^3.0.0
  slider_view: ^1.1.0
  url_launcher: ^6.1.0
  webview_flutter: ^4.2.3
  webview_flutter_android: ^3.9.3
  webview_flutter_wkwebview: ^3.7.3

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.5.3
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  go_router_builder: ^2.3.3
  # intl_utils: ^2.8.4
  json_serializable: ^6.6.1
  riverpod_generator: ^2.3.1
  riverpod_lint: ^2.0.3


flutter:
  uses-material-design: true

  assets:

  # assets start

  # GENERATED CODE - DO NOT MODIFY MANUALLY
  # **************************************************************************
  # Auto generated by https://github.com/fluttercandies/assets_generator
  # **************************************************************************

    - assets/images/

  # assets end
  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/icon_font.ttf

flutter_intl:
  enabled: true
  arb_dir: lib/app/l10n
  output_dir: lib/app/l10n/generated