// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
class Assets {
  const Assets._();
  static const String ASSETS_IMAGES_400_PNG = 'assets/images/400.png';

  static const String ASSETS_IMAGES_404_PNG = 'assets/images/404.png';

  static const String ASSETS_IMAGES_500_PNG = 'assets/images/500.png';

  static const String ASSETS_IMAGES_EMPTY_PNG = 'assets/images/empty.png';

  static const String ASSETS_IMAGES_FAVORITES_EMPTY_PNG =
      'assets/images/favorites_empty.png';

  static const String ASSETS_IMAGES_SEARCH_EMPTY_PNG =
      'assets/images/search_empty.png';

  static const String ASSETS_IMAGES_TIMEOUT_PNG = 'assets/images/timeout.png';

  static const String ASSETS_IMAGES_UNKNOWN_ERROR_PNG =
      'assets/images/unknown_error.png';

  static const String ASSETS_IMAGES_UNKNOWN_PATH_PNG =
      'assets/images/unknown_path.png';
}
